[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version = "cancun"
solc_version = "0.8.25"
optimizer = true
optimize_runs = 20_000_000

bytecode_hash = "none"

via_ir = false

[profile.deploy] # See script/DeploymentBase.sol
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
