# https://taskfile.dev

version: "3"

tasks:
  _generateImports:
    internal: true
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - < TMPL/SwapperDeployer.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}SwapperDeployer.gen.sol
      - < TMPL/SwapperBase.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}SwapperBase.gen.sol
      - < TMPL/For{{.CONSIDERATION}}Swapper.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swapper.gen.sol

  generateImports:
    cmds:
      - for: ['ERC721ForNative', 'MultiERC721ForNative']
        task: _generateImports
        vars:
          TYPE: '{{.ITEM}}'
          CONSIDERATION: 'Native'
      - for: ['ERC721ForERC20', 'MultiERC721ForERC20', 'TMPL'] # TMPL is arbitrarily ERC20, to demonstrate the `currency` field
        task: _generateImports
        vars:
          TYPE: '{{.ITEM}}'
          CONSIDERATION: 'ERC20'

  generateSwapStructBoilerplate:
    dir: "./src/"
    preconditions:
      - test ! -e {{.TYPE}}/{{.TYPE}}Swap.sol
    cmds:
      - < TMPL/TMPLSwap.sol sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swap.sol
          
  generateBoilerplate:
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - task: generateSwapStructBoilerplate

  default:
    cmds:
      - task: generateImports
