# https://taskfile.dev

version: "3"

tasks:
  _generateImports:
    internal: true
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - cp TMPL/TMPLSwapperDeployer.tmpl.sol {{.TYPE}}/{{.TYPE}}SwapperDeployer.gen.sol
      - cp TMPL/TMPLSwapperBase.tmpl.sol {{.TYPE}}/{{.TYPE}}SwapperBase.gen.sol
      - cp TMPL/For{{.CONSIDERATION}}Swapper.tmpl.sol {{.TYPE}}/{{.TYPE}}Swapper.gen.sol
      - sed -i 's|TMPL|{{.TYPE}}|g' {{.TYPE}}/*.gen.sol
      - sed -i 's|.tmpl.sol|.gen.sol|g' {{.TYPE}}/*.gen.sol

  generateImports:
    cmds:
      - for: ['ERC721ForNative', 'MultiERC721ForNative']
        task: _generateImports
        vars:
          TYPE: '{{.ITEM}}'
          CONSIDERATION: 'Native'
      - for: ['ERC721ForERC20', 'MultiERC721ForERC20']
        task: _generateImports
        vars:
          TYPE: '{{.ITEM}}'
          CONSIDERATION: 'ERC20'

  generateSwapStructBoilerplate:
    dir: "./src/"
    preconditions:
      - test ! -e {{.TYPE}}/{{.TYPE}}Swap.sol
    cmds:
      - < TMPL/TMPLSwap.sol sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swap.sol
          
  generateBoilerplate:
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - task: generateSwapStructBoilerplate

  default:
    cmds:
      - task: generateImports
