# https://taskfile.dev

version: "3"

tasks:
  _generateImports:
    internal: true
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - < TMPL/TMPLSwapperDeployer.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}SwapperDeployer.gen.sol
      - < TMPL/TMPLSwapperBase.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}SwapperBase.gen.sol

  _generateSwapperForNative:
    internal: true
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - < TMPL/TMPLForNativeSwapper.sol.tmpl sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swapper.gen.sol

  generateImports:
    cmds:
      - for: ['ERC721ForNative', 'ERC721ForERC20', 'MultiERC721ForNative', 'MultiERC721ForERC20', 'TMPL']
        task: _generateImports
        vars:
          TYPE: '{{.ITEM}}'
      - for: ['ERC721ForNative', 'MultiERC721ForNative']
        task: _generateSwapperForNative
        vars:
          TYPE: '{{.ITEM}}'

  generateImportsForExperimental:
    cmds:
      - task: _generateImports
        vars:
          TYPE: 'Experimental'

  generateSwapStructBoilerplate:
    dir: "./src/"
    preconditions:
      - test ! -e {{.TYPE}}/{{.TYPE}}Swap.sol
    cmds:
      - < TMPL/TMPLSwap.sol sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swap.sol

  generateSwapperBoilerplate:
    dir: "./src/"
    preconditions:
      - test ! -e {{.TYPE}}/{{.TYPE}}Swapper.sol
    cmds:
      - < TMPL/TMPLSwapper.sol sed 's|TMPL|{{.TYPE}}|g' > {{.TYPE}}/{{.TYPE}}Swapper.sol
          
  generateBoilerplate:
    dir: "./src/"
    cmds:
      - mkdir -p {{.TYPE}}
      - task: generateSwapStructBoilerplate
      - task: generateSwapperBoilerplate

  default:
    cmds:
      - task: generateImports
